# Generated by Django 2.2.1 on 2019-05-12 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20190512_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='my_session',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='headline',
        ),
        migrations.AddField(
            model_name='response',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.Choice'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'response')},
        ),
        migrations.DeleteModel(
            name='MySession',
        ),
    ]
