# Generated by Django 2.2.1 on 2019-05-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190512_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='User',
            new_name='user',
        ),
    ]
