# Generated by Django 2.2.1 on 2019-05-12 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190512_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Survey'),
            preserve_default=False,
        ),
    ]
