# Generated by Django 2.0 on 2019-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_question_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_unit',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='icon_class',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
