# Generated by Django 2.2.1 on 2019-05-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190512_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Response'),
        ),
    ]
