# Generated by Django 2.2.1 on 2019-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190512_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='possitve_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_unit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='possitive_or_negative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_type',
            field=models.BooleanField(default=False),
        ),
    ]
