# Generated by Django 2.2.1 on 2019-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190512_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='possitve_count',
            new_name='possitive_count',
        ),
    ]
