# Generated by Django 2.2.1 on 2019-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20190513_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='chart_text',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
