# Generated by Django 2.2.1 on 2019-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_choice_chart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='possitive_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
