# Generated by Django 2.2.1 on 2019-05-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20190513_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='serial_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
